import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from '@/components/layout/Header';
import { ThemeProvider } from '@/providers/theme-provider'
import StarsCanvas from '@/components/ui/stars/Stars'
import Footer from '@/components/layout/Footer'
import { navButtons, navItems } from '@/components/ui/header/navItems'
import dynamic from 'next/dynamic'

const Sidebar = dynamic(() => import('../components/ui/sidebarTest/SidebarTest'), { ssr: false })

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang='en'>
			<body className={`bg-[#161616] overflow-x-hidden`}>
				<ThemeProvider
					attribute='class'
					defaultTheme='dark'
					enableSystem
					disableTransitionOnChange
				>
					<StarsCanvas />
					<Sidebar />
					<Header navItems={navItems} navButtons={navButtons} />
					{children}
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	)
}
