export const newsIdData = [
	{
		id: 1,
		title: 'Новый сервер 1',
		subTitle: 'INFINITUM',
		content: 'Присоединяйтесь к сообществу геймеров...',
		image: '/planeta-1.jpg',
		additionalImages: ['/server-1.svg', '/server-2.svg'],
		footerImage: '/news-1.png',
	},
	{
		id: 2,
		title: 'Новый сервер 2',
		subTitle: 'INFINITUM',
		content: 'Присоединяйтесь к сообществу геймеров...',
		image: '/planet-3.png',
		additionalImages: ['/server-1.svg', '/server-2.svg'],
		footerImage: '/news-1.png',
	},
	{
		id: 3,
		title: 'Новый сервер 3',
		subTitle: 'INFINITUM',
		content: 'Присоединяйтесь к сообществу геймеров...',
		image: '/news-1.png',
		additionalImages: ['/server-1.svg', '/server-2.svg'],
		footerImage: '/news-1.png',
	},
	{
		id: 4,
		title: 'Новый сервер 4',
		subTitle: 'INFINITUM',
		content: 'Присоединяйтесь к сообществу геймеров...',
		image: '/news-2.png',
		additionalImages: ['/server-1.svg', '/server-2.svg'],
		footerImage: '/news-1.png',
	},
]