name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to VDS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_KEY }}
          port: 22

          script: |
            cd ~/infinitum-website

            git pull origin master

            docker build -t infinitum-website .

            docker stop infinitum-website
            docker rm infinitum-website

            docker run -d \
              --name infinitum-website \
              -p 3000:3000 \
              infinitum-website

            docker system prune -af